sudo: required
services:
  - docker

before_install:
  - docker build -t malinois/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true malinois/react-test npm test -- --coverage

after_success:
  - docker build -t malinois/multi-client ./client
  - docker build -t malinois/multi-server ./server
  - docker build -t malinois/multi-worker ./worker
  - docker build -t malinois/multi-nginx ./nginx
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push malinois/multi-client
  - docker push malinois/multi-server
  - docker push malinois/multi-worker
  - docker push malinois/multi-nginx
