version: "3"

services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=postgres
  redis:
    image: "redis:latest"
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app # map from server folder into container /app folder as defined in dockerfile
    environment:
      - REDIS_HOST=redis # name of the service
      - REDIS_PORT=6379 # standard exposed port from redis
      - PGUSER=postgres
      - PGHOST=postgres # name of the service
      - PGDATABASE=postgres
      - PGPASSWORD=postgres
      - PGPORT=5432
    depends_on:
      - redis
      - postgres
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - 3030:80
    depends_on:
      - api
      - client
